### ISSUE TITLE
是否发成npm包

### ISSUE THREAD

**Issue by xxholly32** [Jenniferyingni/vue-cli-plugin-qiankun#3]
现在要搭建一个脚手架的话，还要clone你这个项目，有点不方便

**Comment by Jenniferyingni** [comment]
已发布到npm

主应用生成方式
vue create portal
cd portal
vue add vue-cli-plugin-qiankun-portal

子应用生成方式
vue create demo1
cd demo1
vue add vue-cli-plugin-qiankun-microapp
