### ISSUE TITLE
父子组件传值

### ISSUE THREAD

**Issue by Aliom252181** [Jenniferyingni/vue-cli-plugin-qiankun#4]
请问子传父如何书写？

**Comment by Jenniferyingni** [comment]
你可以在 fns 这里传递一个 setMicro 方法到子应用，接收子应用的入参，然后存到 store 里
![image](https://user-images.githubusercontent.com/18223971/86424205-79e0e980-bd14-11ea-99a1-a8f4df0b21a4.png)

**Comment by Aliom252181** [comment]
@Jenniferyingni thanks，在我更新qiankun2.0.16后，我发现qiankun文档中提供了`initGlobalState(state)`方法,解决了qiankun1.X的这个问题https://qiankun.umijs.org/zh/api#initglobalstatestate。
